language: python
python: "3.5.2"
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
install: make install-requirements 
script: make test
after_success: make codecov
